

export const MODEL_NAME = 'gemini-2.5-flash';

export const PROFESSIONAL_ROLES = [
  "Physician / Doctor",
  "Resident / Intern",
  "Medical Student",
  "Nurse",
  "Nursing Student",
  "Paramedic / EMT",
  "Allied Health Professional",
  "Pharmacist",
  "Healthcare Assistant / Caregiver",
  "Other"
];

export const REGIONS_DATA: Record<string, string[]> = {
  "North America": ["United States", "Canada", "Mexico"],
  "Europe": [
    "United Kingdom", "Germany", "France", "Spain", "Italy", "Netherlands", "Switzerland", "Belgium",
    "Portugal", "Sweden", "Norway", "Denmark", "Finland", "Poland", "Austria", "Ireland", "Greece",
    "Russia", "Ukraine", "Belarus", "Czech Republic", "Hungary", "Romania", "Bulgaria", "Serbia", "Croatia",
    "Slovakia", "Slovenia", "Estonia", "Latvia", "Lithuania", "Moldova", "Bosnia and Herzegovina",
    "Albania", "North Macedonia", "Montenegro", "Iceland", "Luxembourg", "Malta", "Cyprus", "Kosovo"
  ],
  "Central Asia & Caucasus": [
    "Kazakhstan", "Uzbekistan", "Azerbaijan", "Georgia", "Armenia", "Kyrgyzstan", "Tajikistan", "Turkmenistan"
  ],
  "Asia-Pacific": [
    "Australia", "New Zealand", "Japan", "South Korea", "Singapore", "India", "China", "Taiwan",
    "Hong Kong", "Thailand", "Vietnam", "Indonesia", "Malaysia", "Philippines", "Pakistan", "Bangladesh",
    "Sri Lanka", "Nepal", "Mongolia"
  ],
  "Middle East & Africa": [
    "UAE", "Saudi Arabia", "Qatar", "Turkey", "Egypt", "South Africa", "Nigeria", "Kenya", "Morocco",
    "Algeria", "Ethiopia", "Ghana", "Tanzania", "Uganda", "Palestine"
  ],
  "South America": [
    "Brazil", "Argentina", "Chile", "Colombia", "Peru", "Venezuela", "Ecuador", "Bolivia",
    "Uruguay", "Paraguay", "Guyana", "Suriname"
  ],
  "Central America & Caribbean": [
    "Costa Rica", "Panama", "Dominican Republic", "Puerto Rico", "Guatemala", "Honduras",
    "El Salvador", "Nicaragua", "Cuba", "Jamaica", "Haiti", "Bahamas", "Belize", "Trinidad and Tobago"
  ]
};

// Maps countries to their default language code for convenience, 
// though this no longer dictates the voice input language strictly.
export const COUNTRY_TO_LANG_CODE: Record<string, string> = {
  // North America
  "United States": "en-US",
  "Canada": "en-CA",
  "Mexico": "es-MX",

  // Europe
  "United Kingdom": "en-GB",
  "Germany": "de-DE",
  "France": "fr-FR",
  "Spain": "es-ES",
  "Italy": "it-IT",
  "Netherlands": "nl-NL",
  "Switzerland": "de-CH",
  "Belgium": "fr-BE",
  "Portugal": "pt-PT",
  "Sweden": "sv-SE",
  "Norway": "no-NO",
  "Denmark": "da-DK",
  "Finland": "fi-FI",
  "Poland": "pl-PL",
  "Austria": "de-AT",
  "Ireland": "en-IE",
  "Greece": "el-GR",
  "Russia": "ru-RU",
  "Ukraine": "uk-UA",
  "Belarus": "ru-BY",
  "Czech Republic": "cs-CZ",
  "Hungary": "hu-HU",
  "Romania": "ro-RO",
  "Bulgaria": "bg-BG",
  "Serbia": "sr-RS",
  "Croatia": "hr-HR",
  "Slovakia": "sk-SK",
  "Slovenia": "sl-SI",
  "Estonia": "et-EE",
  "Latvia": "lv-LV",
  "Lithuania": "lt-LT",
  "Moldova": "ro-MD",
  "Bosnia and Herzegovina": "bs-BA",
  "Albania": "sq-AL",
  "North Macedonia": "mk-MK",
  "Montenegro": "sr-ME",
  "Iceland": "is-IS",
  "Luxembourg": "fr-LU",
  "Malta": "en-MT",
  "Cyprus": "el-CY",
  "Kosovo": "sq-AL",

  // Central Asia & Caucasus
  "Kazakhstan": "kk-KZ",
  "Uzbekistan": "uz-UZ",
  "Azerbaijan": "az-AZ",
  "Georgia": "ka-GE",
  "Armenia": "hy-AM",
  "Kyrgyzstan": "ky-KG",
  "Tajikistan": "tg-TJ",
  "Turkmenistan": "tk-TM",

  // Asia-Pacific
  "Australia": "en-AU",
  "New Zealand": "en-NZ",
  "Japan": "ja-JP",
  "South Korea": "ko-KR",
  "Singapore": "en-SG",
  "India": "en-IN",
  "China": "zh-CN",
  "Taiwan": "zh-TW",
  "Hong Kong": "zh-HK",
  "Thailand": "th-TH",
  "Vietnam": "vi-VN",
  "Indonesia": "id-ID",
  "Malaysia": "ms-MY",
  "Philippines": "en-PH",
  "Pakistan": "ur-PK",
  "Bangladesh": "bn-BD",
  "Sri Lanka": "si-LK",
  "Nepal": "ne-NP",
  "Mongolia": "mn-MN",

  // Middle East & Africa
  "UAE": "ar-AE",
  "Saudi Arabia": "ar-SA",
  "Qatar": "ar-QA",
  "Turkey": "tr-TR",
  "Egypt": "ar-EG",
  "South Africa": "en-ZA",
  "Nigeria": "en-NG",
  "Kenya": "en-KE",
  "Morocco": "ar-MA",
  "Algeria": "ar-DZ",
  "Ethiopia": "am-ET",
  "Ghana": "en-GH",
  "Tanzania": "sw-TZ",
  "Uganda": "en-UG",
  "Palestine": "ar-PS",

  // South America
  "Brazil": "pt-BR",
  "Argentina": "es-AR",
  "Chile": "es-CL",
  "Colombia": "es-CO",
  "Peru": "es-PE",
  "Venezuela": "es-VE",
  "Ecuador": "es-EC",
  "Bolivia": "es-BO",
  "Uruguay": "es-UY",
  "Paraguay": "es-PY",
  "Guyana": "en-GY",
  "Suriname": "nl-SR",

  // Central America & Caribbean
  "Costa Rica": "es-CR",
  "Panama": "es-PA",
  "Dominican Republic": "es-DO",
  "Puerto Rico": "es-PR",
  "Guatemala": "es-GT",
  "Honduras": "es-HN",
  "El Salvador": "es-SV",
  "Nicaragua": "es-NI",
  "Cuba": "es-CU",
  "Jamaica": "en-JM",
  "Haiti": "fr-HT",
  "Bahamas": "en-BS",
  "Belize": "en-BZ",
  "Trinidad and Tobago": "en-TT"
};

export const VOICE_LANGUAGES: Record<string, string> = {
  "English (US)": "en-US",
  "English (UK)": "en-GB",
  "Spanish (Spain)": "es-ES",
  "Spanish (Latin America)": "es-MX",
  "Russian": "ru-RU",
  "German": "de-DE",
  "French": "fr-FR",
  "Italian": "it-IT",
  "Portuguese (Brazil)": "pt-BR",
  "Portuguese (Portugal)": "pt-PT",
  "Chinese (Mandarin)": "zh-CN",
  "Japanese": "ja-JP",
  "Arabic": "ar-SA",
  "Hindi": "hi-IN"
};


export const DEFAULT_WELCOME_MESSAGE = "Hello, I am MDnexa™ - your guideline-aware medical AI assistant.\nBefore we begin, please ensure your language, country, and region are set correctly in settings to help me follow local medical standards.\nI can help you understand conditions, pathophysiology, differentials and drug suitability for educational purposes.";

// Multilingual Welcome Messages
export const MULTILINGUAL_WELCOME_MESSAGES: Record<string, string> = {
  "Spanish": "Hola, soy MDnexa™, tu asistente médico de IA consciente de las pautas.\nAntes de comenzar, asegúrese de que su idioma, país y región estén configurados correctamente en la configuración para ayudarme a seguir los estándares médicos locales.\nPuedo ayudarte a comprender condiciones, fisiopatología, diferenciales e idoneidad de medicamentos con fines educativos.",
  "French": "Bonjour, je suis MDnexa™ - votre assistant médical IA respectueux des directives.\nAvant de commencer, veuillez vous assurer que votre langue, votre pays et votre région sont correctement définis dans les paramètres pour m'aider à suivre les normes médicales locales.\nJe peux vous aider à comprendre les pathologies, la physiopathologie, les diagnostics différentiels et l'adéquation des médicaments à des fins éducatives.",
  "German": "Hallo, ich bin MDnexa™ - Ihr leitlinienbewusster medizinischer KI-Assistent.\nBevor wir beginnen, stellen Sie bitte sicher, dass Ihre Sprache, Ihr Land und Ihre Region in den Einstellungen korrekt festgelegt sind, damit ich die lokalen medizinischen Standards befolgen kann.\nIch kann Ihnen helfen, Bedingungen, Pathophysiologie, Differentialdiagnosen und Arzneimitteleignung zu Bildungszwecken zu verstehen.",
  "Portuguese": "Olá, sou o MDnexa™ - seu assistente médico de IA orientado por diretrizes.\nAntes de começarmos, certifique-se de que seu idioma, país e região estejam definidos corretamente nas configurações para me ajudar a seguir os padrões médicos locais.\nPosso ajudá-lo a entender condições, fisiopatologia, diferenciais e adequação de medicamentos para fins educacionais.",
  "Italian": "Ciao, sono MDnexa™ - il tuo assistente medico IA consapevole delle linee guida.\nPrima di iniziare, assicurati che la lingua, il paese e la regione siano impostati correttamente nelle impostazioni per aiutarmi a seguire gli standard medici locali.\nPosso aiutarti a comprendere condizioni, fisiopatologia, differenziali e idoneità dei farmaci a scopo educativo.",
  "Russian": "Здравствуйте, я MDnexa™ — ваш медицинский ИИ-ассистент, учитывающий клинические рекомендации.\nПрежде чем начать, пожалуйста, убедитесь, что ваш язык, страна и регион правильно настроены в настройках, чтобы я мог следовать местным медицинским стандартам.\nЯ могу помочь вам понять состояния, патофизиологию, дифференциальную диагностику и пригодность лекарств в образовательных целях.",
  "Chinese": "你好，我是 MDnexa™ - 您的循证医学 AI 助手。\n在我们开始之前，请确保在设置中正确设置了您的语言、国家和地区，以帮助我遵循当地的医疗标准。\n我可以帮助您了解疾病、病理生理学、鉴别诊断和药物适用性，仅供教育目的。",
  "Japanese": "こんにちは、MDnexa™ です。ガイドラインに準拠した医療 AI アシスタントです。\n始める前に、現地の医療基準に従うために、設定で言語、国、地域が正しく設定されていることを確認してください。\n教育目的で、病状、病態生理学、鑑別診断、薬の適合性を理解するお手伝いができます。",
  "Arabic": "مرحبًا، أنا MDnexa™ - مساعدك الطبي الذكي الملتزم بالإرشادات.\nقبل أن نبدأ، يرجى التأكد من ضبط لغتك وبلدك ومنطقتك بشكل صحيح في الإعدادات لمساعدتي في اتباع المعايير الطبية المحلية.\nيمكنني مساعدتك في فهم الحالات، والفيزيولوجيا المرضية، والتشخيص التفريقي، وملاءمة الدواء للأغراض التعليمية.",
  "Hindi": "नमस्ते, मैं MDnexa™ हूँ - आपका दिशानिर्देश-जागरूक चिकित्सा AI सहायक।\nशुरू करने से पहले, कृपया सुनिश्चित करें कि मैं स्थानीय चिकित्सा मानकों का पालन कर सकूँ, इसके लिए सेटिंग्स में आपकी भाषा, देश और क्षेत्र सही ढंग से सेट हैं।\nमैं आपको शैक्षिक उद्देश्यों के लिए स्थितियों, पैथोफिज़ियोलॉजी, अंतर और दवा की उपयुक्तता को समझने में मदद कर सकता हूँ।"
};

export const getWelcomeMessage = (language: string = "English"): string => {
  let message = DEFAULT_WELCOME_MESSAGE;
  const langKey = Object.keys(MULTILINGUAL_WELCOME_MESSAGES).find(key => language.includes(key));

  if (langKey) {
    message = MULTILINGUAL_WELCOME_MESSAGES[langKey];
  }
  return message;
};

export const isWelcomeMessage = (text: string): boolean => {
  if (text === DEFAULT_WELCOME_MESSAGE) return true;
  return Object.values(MULTILINGUAL_WELCOME_MESSAGES).includes(text);
};

export const isArabic = (language: string): boolean => {
  return language.includes("Arabic") || language.includes("ar");
};

export const DEFAULT_QUESTION_POOL = [
  // Cardiology
  "What are the first-line treatments for hypertension in elderly patients according to ESC 2023?",
  "Differential diagnosis for acute chest pain in a 45-year-old male smoker.",
  "Contraindications for prescribing beta-blockers in patients with asthma.",
  "Management of atrial fibrillation: Rate vs Rhythm control strategies.",
  "Interpret the significance of elevated Troponin I levels in non-ACS settings.",
  "Comparing effectiveness of ACE inhibitors vs. ARBs in heart failure with reduced ejection fraction.",
  "Guideline-directed medical therapy for HFrEF: The four pillars.",
  "Management of acute pericarditis: NSAIDs and Colchicine protocols.",
  "Indications for statin therapy in primary prevention of CVD.",
  "Management of stable angina pectoris: Medical therapy vs revascularization.",
  "ECG criteria for diagnosing Left Bundle Branch Block.",
  "Treatment of infective endocarditis: Empiric antibiotic regimens.",
  "Management of hypertensive emergency vs urgency.",
  "Workup for secondary causes of hypertension in young adults.",
  "Anticoagulation strategies for mechanical heart valves.",
  "Diagnosis and management of hypertrophic cardiomyopathy.",
  "Clinical features and management of aortic stenosis.",
  "Risk stratification in ACS: TIMI vs GRACE scores.",
  "Management of cardiogenic shock: Inotropes and mechanical support.",
  "QT prolongation: Drug causes and management.",

  // Respiratory
  "Management guidelines for community-acquired pneumonia in adults (ATS/IDSA).",
  "Treatment of acute asthma exacerbation in emergency settings.",
  "Management of COPD exacerbations according to GOLD guidelines.",
  "Risk stratification for pulmonary embolism (Wells Score).",
  "Diagnosis and treatment of Idiopathic Pulmonary Fibrosis.",
  "Management of spontaneous pneumothorax: Observation vs chest tube.",
  "Interpret pulmonary function tests (PFTs) in restrictive vs obstructive lung disease.",
  "Treatment of hospital-acquired pneumonia (HAP) and VAP.",
  "Management of acute respiratory distress syndrome (ARDS).",
  "Differential diagnosis of chronic cough in non-smokers.",
  "Evaluation of a solitary pulmonary nodule.",
  "Treatment of sarcoidosis: Indications for corticosteroids.",
  "Management of pleural effusion: Transudative vs Exudative.",
  "Cystic Fibrosis: Current modulator therapies.",
  "Diagnosis and management of Obstructive Sleep Apnea.",
  "Treatment of pulmonary hypertension: WHO groups.",
  "Management of hemoptysis: Initial stabilization and workup.",
  "Lung cancer screening guidelines (USPSTF).",
  "Aspirated foreign body in adults: Recognition and removal.",
  "Bronchiectasis: Etiology and long-term management.",

  // Gastroenterology
  "First-line regimens for H. pylori eradication.",
  "Diagnosis of Celiac Disease: Serology vs Biopsy.",
  "Management of acute diverticulitis: Antibiotics vs observation.",
  "Treatment of Clostridioides difficile infection: FDX vs Vanco.",
  "Management of acute gastrointestinal bleeding (Upper vs Lower).",
  "Differential diagnosis of acute abdominal pain in women of childbearing age.",
  "Management of GERD refractory to PPI therapy.",
  "Evaluation of elevated liver enzymes (AST/ALT).",
  "Treatment of Inflammatory Bowel Disease (Crohn's vs UC flare).",
  "Management of acute pancreatitis: Fluids and feeding.",
  "Diagnosis and treatment of SIBO (Small Intestinal Bacterial Overgrowth).",
  "Management of chronic Hepatitis B infection.",
  "Hepatitis C treatment: Direct-acting antivirals.",
  "Cirrhosis: Management of ascites and spontaneous bacterial peritonitis.",
  "Evaluation of dysphagia: Oropharyngeal vs Esophageal.",
  "Management of Irritable Bowel Syndrome (IBS-C vs IBS-D).",
  "Colon cancer screening options and intervals.",
  "Treatment of Wilson's Disease.",
  "Management of hemochromatosis.",
  "Diagnosis of Zollinger-Ellison Syndrome.",

  // Neurology
  "Treatment algorithms for acute migraine attacks.",
  "Management of acute ischemic stroke: tPA and thrombectomy windows.",
  "Differential diagnosis of sudden onset severe headache.",
  "Treatment of status epilepticus: Stepwise approach.",
  "Management of Multiple Sclerosis: Disease-modifying therapies.",
  "Diagnosis and management of Myasthenia Gravis.",
  "Parkinson's Disease: Levodopa vs Dopamine Agonists.",
  "Dementia workup: Reversible causes.",
  "Management of TIA (Transient Ischemic Attack) and secondary prevention.",
  "Guillain-Barre Syndrome: Diagnosis and treatment.",
  "Cluster headache: Acute treatment and prophylaxis.",
  "Management of bacterial meningitis: Empiric antibiotics.",
  "Normal Pressure Hydrocephalus: Triad and treatment.",
  "Bell's Palsy: Corticosteroids and antivirals.",
  "Trigeminal Neuralgia: Pharmacologic management.",
  "Restless Legs Syndrome: Treatment options.",
  "Essential Tremor vs Parkinsonian Tremor.",
  "Management of intracranial hypertension.",
  "Subarachnoid hemorrhage: Complications and management.",
  "ALS (Amyotrophic Lateral Sclerosis): Supportive care.",

  // Endocrinology
  "Diagnostic criteria for Type 2 Diabetes Mellitus (ADA).",
  "Protocols for managing Diabetic Ketoacidosis (DKA).",
  "Evaluation of a thyroid nodule: Bethesda system.",
  "Management of hypothyroidism in pregnancy.",
  "Treatment of hyperthyroidism: Graves' vs Toxic Nodule.",
  "Insulin initiation regimens in Type 2 Diabetes.",
  "Workup for adrenal incidentaloma.",
  "Diagnosis and management of Cushing's Syndrome.",
  "Primary Hyperparathyroidism: Surgical indications.",
  "Management of Addison's Disease (Adrenal Insufficiency).",
  "Polycystic Ovary Syndrome (PCOS): Diagnostic criteria.",
  "Management of gestational diabetes.",
  "Hypoglycemia workup in non-diabetic adults.",
  "Acromegaly: Diagnosis and treatment.",
  "Pheochromocytoma: Pre-operative management.",
  "Diabetes Insipidus: Central vs Nephrogenic.",
  "Osteoporosis treatment: Bisphosphonates and holidays.",
  "Management of Hyperprolactinemia.",
  "SIADH: Diagnosis and fluid management.",
  "Male hypogonadism: TRT indications and risks.",

  // Infectious Disease
  "Signs and symptoms of identifying sepsis (qSOFA vs SIRS).",
  "Antibiotic stewardship for uncomplicated UTIs.",
  "Systemic Inflammatory Response Syndrome (SIRS) criteria.",
  "Treatment of Lyme disease: Early localized vs Disseminated.",
  "Management of febrile neutropenia.",
  "HIV: Antiretroviral therapy initiation.",
  "Oppurtunistic infections in HIV (PCP, Toxo).",
  "Tuberculosis: Latent vs Active treatment regimens.",
  "Malaria prophylaxis and treatment options.",
  "Management of infective arthritis (Septic Joint).",
  "Syphilis: Stages and treatment (Primary, Secondary, Neuro).",
  "Treatment of Gonorrhea and Chlamydia co-infection.",
  "Infectious Mononucleosis: Diagnosis and complications.",
  "Zoonotic diseases: Rabies PEP protocols.",
  "Dengue Fever: Warning signs and management.",
  "Invasive Fungal Infections: Candida and Aspergillus.",
  "Infection control for MDR organisms (MRSA, VRE, ESBL).",
  "Adult immunization schedule (Pneumococcal, Zoster).",
  "Travel medicine: Vaccines and precautions.",
  "COVID-19: Current therapeutic guidelines.",

  // Nephrology & Urology
  "Management of chronic kidney disease (CKD) stages 1-3.",
  "Approach to the patient with hyponatremia.",
  "Management of hyperkalemia in emergency department.",
  "Acute Kidney Injury (AKI): Prerenal vs Intrinsic vs Postrenal.",
  "Nephrotic vs Nephritic Syndrome differences.",
  "Treatment of benign prostatic hyperplasia (BPH).",
  "Management of kidney stones <5mm vs >10mm.",
  "Workup for microscopic hematuria.",
  "Polycystic Kidney Disease: Management and complications.",
  "Glomerulonephritis: IgA Nephropathy diagnosis.",
  "Renal Tubular Acidosis (Types 1, 2, 4).",
  "Dialysis indications (AEIOU).",
  "Management of prostatitis: Acute vs Chronic.",
  "Erectile Dysfunction: Phosphodiesterase inhibitors.",
  "Testicular torsion: Acute management.",

  // Rheumatology & Immunology
  "Treatment of acute gout flares vs Urate lowering therapy.",
  "Rheumatoid Arthritis: DMARDs initiation.",
  "Systemic Lupus Erythematosus (SLE): Diagnostic criteria.",
  "Management of Giant Cell Arteritis (Temporal Arteritis).",
  "Fibromyalgia: Non-pharmacologic and pharmacologic management.",
  "Sjogren's Syndrome: Diagnosis and symptom management.",
  "Psoriatic Arthritis: Treatment options.",
  "Ankylosing Spondylitis: TNF inhibitors.",
  "Polymyalgia Rheumatica: Steroid tapering.",
  "Vasculitis overview: ANCA-associated.",
  "Systemic Sclerosis (Scleroderma): Management.",
  "Evaluation of positive ANA.",
  "Gout vs Pseudogout (CPPD).",
  "Reactive Arthritis (Reiter's).",
  "Behcet's Disease: Clinical features.",

  // Hematology & Oncology
  "Differential diagnosis of microcytic anemia.",
  "Workup for macrocytic anemia (B12 vs Folate).",
  "Management of Deep Vein Thrombosis (DVT).",
  "Anticoagulation reversal agents (Warfarin, DOACs).",
  "Sickle Cell Disease: Management of vaso-occlusive crisis.",
  "Thrombocytopenia workup (ITP vs TTP).",
  "Multiple Myeloma: CRAB criteria.",
  "Chronic Lymphocytic Leukemia (CLL): Watch and wait.",
  "Tumor Lysis Syndrome: Prophylaxis and treatment.",
  "Neutropenic fever in cancer patients.",
  "Breast Cancer screening guidelines.",
  "Prostate Cancer screening (PSA debate).",
  "Iron deficiency anemia: Oral vs IV iron.",
  "Hemophilia A vs B.",
  "Polycythemia Vera: Diagnosis.",

  // Pharmacology & Interactions
  "Drug interactions: CYP450 inhibitors and inducers.",
  "Serotonin Syndrome: Symptoms and management.",
  "Digoxin toxicity: ECG changes and reversal.",
  "Acetaminophen overdose: Rumack-Matthew nomogram.",
  "Warfarin interactions with antibiotics.",
  "Statins: Mechanism and management of myalgia.",
  "Beta-blocker overdose management.",
  "Calcium channel blocker overdose.",
  "Tricyclic Antidepressant (TCA) toxicity.",
  "Lithium toxicity and monitoring.",
  "Opioid conversion calculations (MME).",
  "Antibiotic side effects: Fluoroquinolones and tendons.",
  "Aminoglycoside nephrotoxicity and ototoxicity.",
  "Corticosteroid tapering scheudles.",
  "Anticholinergic burden in the elderly.",
  "Metformin and lactic acidosis risk.",
  "SGLT2 inhibitors: Benefits beyond diabetes.",
  "GLP-1 agonists: Side effect profile.",
  "Diuretic resistance mechanisms.",
  "Antiplatelet therapy: DAPT duration.",
  "DOACs dosing in renal failure.",
  "Vancomycin dosing and trough monitoring.",
  "Linezolid and serotonin syndrome risk.",
  "MAO inhibitors and tyramine reaction.",
  "Teratogenic drugs to avoid in pregnancy.",
  "Drugs causing QT prolongation.",
  "Checklist for prescribing in renal impairment.",
  "Pharmacology of sedation (Propofol vs Midazolam).",
  "Local anesthetic toxicity (LAST).",
  "Managing polypharmacy in geriatrics.",

  // Emergency & Trauma
  "ACLS guidelines for stable wide-complex tachycardia.",
  "Management of anaphylaxis: Epinephrine dosing.",
  "Sepsis bundles: 1-hour targets.",
  "Trauma: ABCDE primary survey.",
  "Glasgow Coma Scale (GCS) calculation.",
  "Burns: Parkland formula for fluid resuscitation.",
  "Management of acute poisoning (General approach).",
  "Carbon monoxide poisoning.",
  "Hypothermia management protocols.",
  "Heat stroke vs Heat exhaustion.",
  "Snake bite management.",
  "Dog and cat bite antibiotics.",
  "Head injury: Canadian CT Head Rule.",
  "C-spine clearance criteria (NEXUS).",
  "Tension pneumothorax decompression.",
  "Pericardiocentesis technique.",
  "Intraosseous access indications.",
  "Rapid Sequence Intubation (RSI) medications.",
  "Management of epistaxis.",
  "Eye emergencies: Chemical burn irrigation.",

  // Pediatrics
  "First-line antibiotics for acute otitis media in children.",
  "Pediatric immunization schedule.",
  "Management of febrile seizures.",
  "Croup: Dexamethasone and Epinephrine.",
  "Bronchiolitis: Supportive care guidelines.",
  "Kawasaki Disease: Diagnosis and treatment.",
  "Neonatal jaundice: Phototherapy thresholds.",
  "Pyloric stenosis: Electrolyte abnormalities.",
  "Intussusception: Diagnosis and reduction.",
  "Pediatric dehydration: Oral rehydration vs IV.",
  "Failure to thrive workup.",
  "Hand, Foot, and Mouth Disease.",
  "Streptococcal pharyngitis (Strep throat) scoring.",
  "Developmental milestones red flags.",
  "SIDS prevention guidelines.",

  // ObGyn
  "Clinical features and management of preeclampsia.",
  "Ectopic pregnancy: Methotrexate vs Surgery.",
  "Postpartum hemorrhage management.",
  "Contraception options and contraindications (MEC).",
  "Pelvic Inflammatory Disease (PID) treatment.",
  "Abnormal Uterine Bleeding (PALM-COEIN).",
  "Menopause management: HRT risks/benefits.",
  "Endometriosis diagnosis and medical management.",
  "Screening for cervical cancer (Pap smear).",
  "Management of Group B Strep in pregnancy.",

  // Psychiatry
  "Treatment options for Generalized Anxiety Disorder (GAD).",
  "Management of Major Depressive Disorder in adolescents.",
  "Management of alcohol withdrawal syndrome (CIWA).",
  "Bipolar Disorder: Lithium vs Valproate.",
  "Schizophrenia: First vs Second generation antipsychotics.",
  "Acute agitation management.",
  "Suicide risk assessment.",
  "Borderline Personality Disorder: DBT.",
  "PTSD: Pharmacotherapy and Psychotherapy.",
  "Eating disorders: Refeeding syndrome risk."
];

// Multilingual Question Pools
// Each pool contains a subset of translated high-yield questions
export const MULTILINGUAL_QUESTION_POOLS: Record<string, string[]> = {
  "Spanish": [
    "Tratamiento de primera línea para la hipertensión en adultos mayores.",
    "Manejo de la cetoacidosis diabética según guías actuales.",
    "Protocolo para el manejo de la sepsis y shock séptico (Surviving Sepsis).",
    "Diagnóstico diferencial del dolor torácico agudo en urgencias.",
    "Tratamiento de la exacerbación aguda de EPOC.",
    "Manejo de la fibrilación auricular: Control de ritmo vs frecuencia.",
    "Guías para el tratamiento de la insuficiencia cardíaca con fracción de eyección reducida.",
    "Abordaje de la lesión renal aguda (AKI) y sus causas.",
    "Tratamiento empírico de la neumonía adquirida en la comunidad.",
    "Criterios de diagnóstico para diabetes mellitus tipo 2.",
    "Manejo de la hemorragia digestiva alta varicosa y no varicosa.",
    "Protocolo de actuación ante un ictus isquémico agudo (ventana terapéutica).",
    "Tratamiento de la infección del tracto urinario complicada.",
    "Manejo de la preeclampsia y eclampsia.",
    "Evaluación y tratamiento de la cefalea tipo migraña.",
    "Causas y tratamiento de la hiperpotasemia grave.",
    "Diagnóstico y manejo del tromboembolismo pulmonar.",
    "Tratamiento de la pancreatitis aguda: Fluidoterapia y nutrición.",
    "Abordaje de la anemia microcítica.",
    "Guías para el manejo del asma bronquial en adultos.",
    "Tratamiento de la depresión mayor resistente.",
    "Manejo inicial del paciente politraumatizado (ATLS).",
    "Diagnóstico diferencial de ictericia obstructiva.",
    "Tratamiento de la artritis reumatoide: DMARDs biológicos.",
    "Manejo de la crisis tirotóxica.",
    "Indicaciones de diálisis en urgencias.",
    "Profilaxis post-exposición para VIH.",
    "Manejo del síndrome coronario agudo sin elevación del ST.",
    "Tratamiento de la meningitis bacteriana aguda.",
    "Evaluación del nódulo tiroideo y criterios de PAAF."
  ],
  "French": [
    "Prise en charge de l'hypertension artérielle selon les dernières recommandations.",
    "Protocole de traitement de l'acidocétose diabétique.",
    "Conduite à tenir devant une douleur thoracique aiguë.",
    "Traitement de première ligne de l'insuffisance cardiaque à fraction d'éjection réduite.",
    "Prise en charge de la fibrillation atriale : Contrôle du rythme vs fréquence.",
    "Traitement des exacerbations aiguës de BPCO.",
    "Recommandations pour l'antibiothérapie des pneumonies communautaires.",
    "Diagnostic et traitement de l'embolie pulmonaire.",
    "Prise en charge du sepsis et du choc septique (Guidelines).",
    "Traitement de l'accident vasculaire cérébral ischémique en phase aiguë.",
    "La prise en charge de l'hémorragie digestive haute.",
    "Traitement des infections urinaires compliquées.",
    "Diagnostic différentiel des anémies microcytaires.",
    "Protocole de prise en charge de l'infarctus du myocarde (STEMI).",
    "Traitement de la pancréatite aiguë : Hydratation et nutrition.",
    "Conduite à tenir devant une hyperkaliémie sévère.",
    "Prise en charge de la pré-éclampsie sévère.",
    "Traitement de la crise d'asthme aiguë aux urgences.",
    "Algorithme de traitement du diabète de type 2.",
    "Prise en charge de l'insuffisance rénale aiguë.",
    "Traitement de fond de la migraine et gestion de la crise.",
    "Diagnostic et traitement de l'hépatite virale chronique.",
    "Prise en charge de la polyarthrite rhumatoïde.",
    "Traitement des troubles dépressifs majeurs.",
    "Conduite à tenir devant un nodule pulmonaire solitaire.",
    "Traitement de la méningite bactérienne communautaire.",
    "Prise en charge de l'état de mal épileptique.",
    "Traitement de l'hypothyroïdie et ajustement de la lévothyroxine.",
    "Recommandations pour le dépistage du cancer colorectal.",
    "Traitement des infections sexuellement transmissibles (Gonorrhée/Chlamydia)."
  ],
  "German": [
    "Leitlinien zur Behandlung der arteriellen Hypertonie.",
    "Management der diabetischen Ketoazidose (DKA).",
    "Therapie der akuten Herzinsuffizienz und HFrEF.",
    "Diagnostik und Therapie der Lungenembolie.",
    "Behandlung der ambulant erworbenen Pneumonie (CAP).",
    "Management von Vorhofflimmern: Frequenz- vs. Rhythmuskontrolle.",
    "Therapiealgorithmus beim akuten Koronarsyndrom (ACS).",
    "Vorgehen bei akuter Niereninsuffizienz (AKI).",
    "Sepsis-Leitlinien: Früherkennung und Initialtherapie.",
    "Behandlung des akuten ischämischen Schlaganfalls (Lyse/Thrombektomie).",
    "Management der akuten oberen gastrointestinalen Blutung.",
    "Therapie der chronisch obstruktiven Lungenerkrankung (COPD) Exazerbation.",
    "Diagnostik und Therapie der tiefen Beinvenenthrombose.",
    "Behandlung der komplizierten Harnwegsinfektion.",
    "Vorgehen bei Hyperkaliämie Notfällen.",
    "Diagnostik und Therapie der akuten Pankreatitis.",
    "Leitlinien zur Behandlung von Asthma bronchiale.",
    "Therapieoptionen bei Typ-2-Diabetes mellitus.",
    "Management der Präeklampsie und Eklampsie.",
    "Abklärung und Therapie der Anämie.",
    "Behandlung der bakteriellen Meningitis.",
    "Therapie der rheumatoiden Arthritis: Basistherapeutika.",
    "Vorgehen bei unklarem Abdomen.",
    "Schilddrüsenerkrankungen: Hypothyreose und Hyperthyreose Management.",
    "Notfallbehandlung des Status epilepticus.",
    "Diagnostik und Therapie von chronisch entzündlichen Darmerkrankungen.",
    "Behandlung von Angststörungen und Depressionen.",
    "Vorgehen bei Schädel-Hirn-Trauma.",
    "Management von Elektrolytstörungen (Hyponatriämie).",
    "Postexpositionsprophylaxe bei HIV."
  ],
  "Portuguese": [
    "Diretrizes para o tratamento da hipertensão arterial sistêmica.",
    "Manejo da cetoacidose diabética em emergência.",
    "Protocolo de tratamento da insuficiência cardíaca (ICFER).",
    "Abordagem da dor torácica aguda e síndrome coronariana.",
    "Tratamento da exacerbação da DPOC (GOLD).",
    "Manejo da fibrilação atrial: Controle de ritmo vs frequência.",
    "Recomendações para pneumonia adquirida na comunidade.",
    "Diagnóstico e tratamento do tromboembolismo pulmonar.",
    "Protocolo de sepse e choque séptico.",
    "Tratamento do acidente vascular cerebral isquêmico agudo.",
    "Manejo da hemorragia digestiva alta.",
    "Terapia para infecção do trato urinário complicada.",
    "Abordagem da lesão renal aguda (LRA).",
    "Tratamento da asma aguda na emergência.",
    "Manejo da pancreatite aguda leve e grave.",
    "Tratamento da hipercalemia severa.",
    "Diagnóstico e manejo da pré-eclâmpsia.",
    "Diretrizes para o tratamento do diabetes tipo 2.",
    "Abordagem das anemias (ferropriva, megaloblástica).",
    "Tratamento da meningite bacteriana aguda.",
    "Manejo da insuficiência hepática e cirrose descompensada.",
    "Tratamento de manutenção da artrite reumatoide.",
    "Abordagem da cefaleia e enxaqueca.",
    "Manejo do hipotireoidismo e hipertireoidismo.",
    "Tratamento da depressão e transtornos de ansiedade.",
    "Protocolo de reanimação cardiopulmonar (ACLS).",
    "Avaliação do nódulo pulmonar solitário.",
    "Tratamento da doença do refluxo gastroesofágico (DRGE).",
    "Manejo de crises epilépticas e estado de mal.",
    "Profilaxia de TVP em pacientes internados."
  ],
  "Italian": [
    "Linee guida per il trattamento dell'ipertensione arteriosa.",
    "Gestione della chetoacidosi diabetica in pronto soccorso.",
    "Terapia dello scompenso cardiaco a frazione di eiezione ridotta.",
    "Diagnosi differenziale del dolore toracico acuto.",
    "Trattamento delle riacutizzazioni della BPCO.",
    "Gestione della fibrillazione atriale: Controllo del ritmo vs frequenza.",
    "Protocollo per la polmonite acquisita in comunità.",
    "Diagnosi e terapia dell'embolia polmonare.",
    "Linee guida Surviving Sepsis Campaign.",
    "Trattamento dell'ictus ischemico acuto (trombolisi).",
    "Gestione dell'emorragia digestiva superiore.",
    "Terapia delle infezioni delle vie urinarie complicate.",
    "Approccio all'insufficienza renale acuta.",
    "Trattamento dell'asma bronchiale acuto.",
    "Gestione della pancreatite acuta.",
    "Trattamento dell'iperkaliemia grave.",
    "Protocollo per pre-eclampsia ed eclampsia.",
    "Terapia farmacologica del diabete mellito di tipo 2.",
    "Diagnosi e cura delle anemie.",
    "Trattamento della meningite batterica.",
    "Gestione della cirrosi epatica e delle sue complicanze.",
    "Terapia dell'artrite reumatoide e malattie autoimmuni.",
    "Trattamento dell'emicrania e cefalea a grappolo.",
    "Gestione delle disfunzioni tiroidee.",
    "Terapia della depressione maggiore.",
    "Algoritmo ACLS per l'arresto cardiaco.",
    "Valutazione del nodulo tiroideo.",
    "Trattamento della malattia da reflusso gastroesofageo.",
    "Gestione dello stato di male epilettico.",
    "Profilassi del tromboembolismo venoso."
  ],
  "Russian": [
    "Первая линия терапии артериальной гипертензии.",
    "Протокол лечния диабетического кетоацидоза.",
    "Ведение пациентов с сердечной недостаточностью (HFrEF).",
    "Дифференциальная диагностика острой боли в груди.",
    "Лечение обострения ХОБЛ (GOLD рекомендации).",
    "Фибрилляция предсердий: Контроль ритма или частоты.",
    "Антибиотикотерапия внебольничной пневмонии.",
    "Диагностика и лечение тромбоэмболии легочной артерии.",
    "Современные рекомендации по лечению сепсиса.",
    "Терапия острого ишемического инсульта.",
    "Тактика при желудочно-кишечном кровотечении.",
    "Лечение осложненных инфекций мочевыводящих путей.",
    "Подход к лечению острого повреждения почек (ОПП).",
    "Купирование приступа бронхиальной астмы.",
    "Лечение острого панкреатита: инфузионная терапия.",
    "Неотложная помощь при гиперкалиемии.",
    "Ведение беременности с преэклампсией.",
    "Алгоритм лечения сахарного диабета 2 типа.",
    "Дифференциальная диагностика анемий.",
    "Лечение бактериального менингита.",
    "Ведение пациентов с циррозом печени.",
    "Базисная терапия ревматоидного артрита.",
    "Лечение мигрени и головной боли напряжения.",
    "Диагностика и лечение гипотиреоза.",
    "Терапия большого депрессивного расстройства.",
    "Сердечно-легочная реанимация (ACLS).",
    "Тактика при узловом зобе.",
    "Лечение гастроэзофагеальной рефлюксной болезни (ГЭРБ).",
    "Купирование эпилептического статуса.",
    "Антикоагулянтная терапия при ТГВ."
  ],
  "Chinese": [
    "高血压的最新治疗指南。",
    "糖尿病酮症酸中毒 (DKA) 的急诊处理流程。",
    "射血分数降低的心力衰竭 (HFrEF) 的药物治疗。",
    "急性胸痛的鉴别诊断与处理。",
    "慢性阻塞性肺疾病 (COPD) 急性加重的管理。",
    "心房颤动管理：节律控制与心室率控制。",
    "社区获得性肺炎 (CAP) 的经验性抗生素治疗。",
    "肺栓塞的诊断与抗凝治疗。",
    "脓毒症和感染性休克的治疗指南 (Surviving Sepsis).",
    "急性缺血性脑卒中的溶栓与取栓治疗。",
    "上消化道出血的紧急处理及内镜治疗。",
    "复杂性尿路感染的治疗方案。",
    "急性肾损伤 (AKI) 的评估与处理。",
    "支气管哮喘急性发作的急诊救治。",
    "急性胰腺炎的液体复苏与营养支持。",
    "严重高钾血症的紧急处理。",
    "子痫前期的诊断与产科处理。",
    "2型糖尿病的降糖药物选择流程。",
    "贫血的鉴别诊断流程（缺铁性 vs 巨幼细胞性）。",
    "细菌性脑膜炎的经验性治疗。",
    "肝硬化失代偿期并发症的处理。",
    "类风湿关节炎的生物制剂治疗。",
    "偏头痛的急性期治疗与预防。",
    "甲状腺功能减退与亢进的管理。",
    "重度抑郁症的药物治疗选择。",
    "心肺复苏及高级心血管生命支持 (ACLS).",
    "甲状腺结节的评估与细针穿刺指征。",
    "胃食管反流病 (GERD) 的阶梯治疗。",
    "癫痫持续状态的紧急终止。",
    "深静脉血栓 (DVT) 的预防与治疗。"
  ],
  "Japanese": [
    "成人の高血圧に対する第一選択薬ガイドライン。",
    "糖尿病性ケトアシドーシス (DKA) の管理プロトコル。",
    "駆出率が低下した心不全 (HFrEF) の薬物療法。",
    "救急外来における急性胸痛の鑑別診断。",
    "COPD急性増悪の治療ガイドライン。",
    "心房細動の管理：レートコントロール vs リズムコントロール。",
    "市中肺炎のエンピリックな抗菌薬治療。",
    "肺塞栓症の診断と抗凝固療法。",
    "敗血症および敗血症性ショックの治療ガイドライン。",
    "急性虚血性脳卒中のt-PAおよび血栓回収療法。",
    "上部消化管出血の緊急対応と内視鏡治療。",
    "複雑性尿路感染症の治療戦略。",
    "急性腎障害 (AKI) の評価と管理。",
    "気管支喘息発作の救急対応。",
    "急性膵炎の輸液療法と栄養管理。",
    "重度高カリウム血症の緊急治療。",
    "妊娠高血圧症候群（子癇前症）の管理。",
    "2型糖尿病の治療アルゴリズム。",
    "小球性貧血および大球性貧血の鑑別。",
    "細菌性髄膜炎の初期治療。",
    "非代償性肝硬変の合併症管理。",
    "関節リウマチの薬物療法（生物学的製剤）。",
    "片頭痛の急性期治療と予防療法。",
    "甲状腺機能低下症および亢進症の管理。",
    "大うつ病性障害の薬物療法。",
    "二次救命処置 (ACLS) のガイドライン。",
    "甲状腺結節の評価と生検適応。",
    "胃食道逆流症 (GERD) の管理。",
    "てんかん重積状態の治療プロトコル。",
    "深部静脈血栓症 (DVT) の予防と治療。"
  ],
  "Arabic": [
    "مبادئ توجيهية لعلاج ارتفاع ضغط الدم لدى البالغين.",
    "بروتوكول إدارة الحماض الكيتوني السكري (DKA).",
    "العلاج الدوائي لفشل القلب مع انخفاض كسر القذف (HFrEF).",
    "التشخيص التفريقي لألم الصدر الحاد في الطوارئ.",
    "علاج تفاقم مرض الانسداد الرئوي المزمن (COPD).",
    "إدارة الرجفان الأذيني: التحكم في المعدل مقابل النظم.",
    "المضادات الحيوية التجريبية للالتهاب الرئوي المكتسب من المجتمع.",
    "تشخيص وعلاج الانصمام الرئوي.",
    "مبادئ توجيهية لعلاج الإنتان والصدمة الإنتانية.",
    "علاج السكتة الدماغية الإقفارية الحادة.",
    "إدارة نزيف الجهاز الهضمي العلوي.",
    "علاج التهابات المسالك البولية المعقدة.",
    "تقييم وإدارة القصور الكلوي الحاد (AKI).",
    "علاج نوبات الربو الحادة في الطوارئ.",
    "علاج التهاب البنكرياس الحاد: السوائل والتغذية.",
    "الإدارة الطارئة لفرط بوتاسيوم الدم الشديد.",
    "إدارة تسمم الحمل (مقدمات الارتعاج).",
    "خوارزمية علاج داء السكري من النوع الثاني.",
    "التشخيص التفريقي لفقر الدم (الأنيميا).",
    "علاج التهاب السحايا الجرثومي.",
    "إدارة مضاعفات تليف الكبد.",
    "علاج التهاب المفاصل الروماتويدي.",
    "علاج الصداع النصفي والوقاية منه.",
    "إدارة قصور الغدة الدرقية وفرط نشاطها.",
    "الخيارات العلاجية للاكتئاب الشديد.",
    "بروتوكولات دعم الحياة القلبي الوعائي المتقدم (ACLS).",
    "تقييم عقيدات الغدة الدرقية.",
    "علاج مرض الارتجاع المعدي المريئي (GERD).",
    "طوارئ الحالة الصرعية.",
    "الوقاية من وعلاج تجلط الأوردة العميقة (DVT)."
  ],
  "Hindi": [
    "उच्च रक्तचाप के प्रबंधन के लिए नवीनतम दिशानिर्देश।",
    "डायबिटिक कीटोएसिडोसिस (DKA) का आपातकालीन उपचार।",
    "हार्ट फेलियर (HFrEF) के लिए चिकित्सा चिकित्सा।",
    "तीव्र सीने में दर्द का विभेदक निदान।",
    "COPD के तीव्र exacerbation का प्रबंधन।",
    "एट्रियल फाइब्रिलेशन: दर बनाम लय नियंत्रण।",
    "कम्युनिटी-एक्वायर्ड निमोनिया के लिए एंटीबायोटिक उपचार।",
    "पल्मोनरी एम्बोलिज्म का निदान और उपचार।",
    "सेप्सis और सेप्टिक शॉक (Surviving Sepsis) दिशानिर्देश।",
    "तीव्र इस्केमिक स्ट्रोक का थ्रोम्बोलिसिस उपचार।",
    "ऊपरी गैस्ट्रोइंटेस्टाइनल रक्तस्राव का प्रबंधन।",
    "जटिल मूत्र पथ के संक्रमण (UTI) का उपचार।",
    "तीव्र गुर्दे की चोट (AKI) का मूल्यांकन और प्रबंधन।",
    "तीव्र अस्थमा हमले का आपातकालीन उपचार।",
    "तीव्र अग्नाशयशोथ (Acute Pancreatitis) का प्रबंधन।",
    "गंभीर हाइपरकेलेमिया (Hyperkalemia) का आपातकालीन उपचार।",
    "प्री-एक्लेमप्सिया और एक्लेमप्सिया का प्रबंधन।",
    "टाइप 2 मधुमेह के लिए उपचार एल्गोरिदम।",
    "एनीमिया के प्रकार और उनका निदान।",
    "बैक्टीरियल मेनिन्जाइटिस का अनुभवजन्य उपचार।",
    "लिवर सिरोसिस और इसकी जटिलताओं का प्रबंधन।",
    "रूमेटाइड अर्थराइटिस के लिए उपचार विकल्प।",
    "माइग्रेन का निदान और उपचार।",
    "हाइपोथायरायडिज्म और हाइपरथायरायडिज्म का प्रबंधन।",
    "प्रमुख अवसाद (Major Depression) का औषधीय उपचार।",
    "कार्डियक अरेस्ट और ACLS प्रोटोकॉल।",
    "थायराइड नोड्यूल का मूल्यांकन।",
    "गैस्ट्रोएसोफेगल रिफ्लक्स रोग (GERD) का उपचार।",
    "स्टेटस एपिलेप्टिकस (Status Epilepticus) का प्रबंधन।",
    "डीप वेन थ्रोम्बोसिस (DVT) का निदान और उपचार।"
  ]
};

export const getRandomQuestions = (count: number = 4, language: string = "English"): string[] => {
  // Check if we have a mapped pool for the language
  // We check mapping keys or try to match names roughly
  let pool = DEFAULT_QUESTION_POOL;

  // Simple key matching (e.g. "Spanish" -> "Spanish")
  // Also handle "Spanish (Latin America)" -> "Spanish"
  const langKey = Object.keys(MULTILINGUAL_QUESTION_POOLS).find(key => language.includes(key));

  if (langKey) {
    pool = MULTILINGUAL_QUESTION_POOLS[langKey];
  }

  // Shuffle and slice
  const shuffled = [...pool].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
};

export interface ToolData {
  id: string;
  name: string;
  description: string;
  iconPath: string;
  access: 'free' | 'waitlist';
  status?: 'active' | 'inactive';
  baseColor: string;
  accentColor: string;
}

export const TOOLS_DATA: ToolData[] = [
  // --- FREE TOOLS ---
  {
    id: 'dictionary',
    name: 'Medical Dictionary',
    description: 'Instant definitions for thousands of medical terms, acronyms, and procedures.',
    iconPath: '/icons/tool-dictionary.png',
    status: 'active',
    access: 'free',
    baseColor: '#E8F5F2',
    accentColor: '#2FA4A9'
  },
  {
    id: 'icd10',
    name: 'ICD-10 Code Checker',
    description: 'Find precise codes with rationale, refinements, and global standards (CM/GM/AM/etc).',
    iconPath: '/icons/tool-icd10.png',
    status: 'active',
    access: 'free',
    baseColor: '#FFF4E5',
    accentColor: '#F4A261'
  },
  {
    id: 'drug_checker',
    name: 'Quick Drug Checker',
    description: 'Rapid clinical summaries: Dosing, Interactions, Renal adjustments & Contraindications.',
    iconPath: '/icons/tool-drug-checker.png',
    status: 'active',
    access: 'free',
    baseColor: '#FDECEC',
    accentColor: '#E76F51'
  },

  // --- PAID TOOLS ---
  {
    id: 'mdnexa-calc',
    name: 'MDnexa Calc',
    description: 'Reliable medical calculators for everyday clinical decision-making.',
    iconPath: '/icons/tool-calc.png',
    access: 'waitlist',
    baseColor: '#EFF4FF',
    accentColor: '#0B5ED7'
  },
  {
    id: 'mdnexa-labs',
    name: 'MDnexa Labs',
    description: 'Explain lab abnormalities and guide appropriate correction steps in clinical context.',
    iconPath: '/icons/tool-labs.png',
    access: 'waitlist',
    baseColor: '#ECFDF5',
    accentColor: '#0F766E'
  },
  {
    id: 'mdnexa-scores',
    name: 'MDnexa Scores',
    description: 'Evidence-based clinical scores, explained and applied correctly.',
    iconPath: '/icons/tool-scores.png',
    access: 'waitlist',
    baseColor: '#EEF2FF',
    accentColor: '#4338CA'
  },
  {
    id: 'mdnexa-drugs',
    name: 'MDnexa Drugs',
    description: 'Comprehensive drug insights including mechanisms, dosing, and interactions.',
    iconPath: '/icons/tool-drugs-waitlist.png',
    access: 'waitlist',
    baseColor: '#FDF2F4',
    accentColor: '#7A1E2B'
  },
  {
    id: 'mdnexa-ddx',
    name: 'MDnexa DDx',
    description: 'Structured differential diagnoses built from symptoms and clinical context.',
    iconPath: '/icons/tool-ddx.png',
    access: 'waitlist',
    baseColor: '#F5F3FF',
    accentColor: '#5B21B6'
  },
  {
    id: 'mdnexa-docu',
    name: 'MDnexa Docu',
    description: 'Turn key clinical details into clear, structured medical documentation.',
    iconPath: '/icons/tool-docu.png',
    access: 'waitlist',
    baseColor: '#F8FAFC',
    accentColor: '#334155'
  },
  {
    id: 'mdnexa-translate',
    name: 'MDnexa Translate',
    description: 'Accurate medical translation across languages, preserving clinical meaning.',
    iconPath: '/icons/tool-translate.png',
    access: 'waitlist',
    baseColor: '#ECFEFF',
    accentColor: '#0F4C5C'
  }
];